### PR TITLE
Update Cofh Core

### PR DESCRIPTION
**Pull request by Kirynn**
Fixes https://github.com/MechOrigin/NTC2/issues/8

### CODE REVIEW

**Review by MechOrigin — APPROVED** [review]
Looks good! Thanks

**Review by MechOrigin — APPROVED** [review]
Looks good too!

**Review by MechOrigin — APPROVED** [review]
just deleting random garbage? ok, thx :)

**Review by MechOrigin — COMMENTED** [review]
I'm going to actually update cofh in the next release to cofh_core-1.16.5-1.4.2.9.jar
Hopefully no crashes or bugs.

**Comment by Kirynn** [comment]
> just deleting random garbage? ok, thx :)

Never contributed to a modpack, not entirely sure what I'm doing lol.

**Pull request merged**
